// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM6-bzcHqUm-QM4ocv4Spy-ESyOHI1oi8',
    appId: '1:1094370169228:web:7921ec6998865dc51e06a9',
    messagingSenderId: '1094370169228',
    projectId: 'lifelink-a3cbe',
    authDomain: 'lifelink-a3cbe.firebaseapp.com',
    storageBucket: 'lifelink-a3cbe.firebasestorage.app',
    measurementId: 'G-Z87PCV84WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhqxJO13VHiHFEuIInQZN0wolU1Vt-NQ4',
    appId: '1:1094370169228:android:f7f3211787436c981e06a9',
    messagingSenderId: '1094370169228',
    projectId: 'lifelink-a3cbe',
    storageBucket: 'lifelink-a3cbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8m529zR6Rbf9FqDwzrOsin0c0Jj6ewj8',
    appId: '1:1094370169228:ios:1845a568848339751e06a9',
    messagingSenderId: '1094370169228',
    projectId: 'lifelink-a3cbe',
    storageBucket: 'lifelink-a3cbe.firebasestorage.app',
    iosBundleId: 'com.example.organAndBloodDonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8m529zR6Rbf9FqDwzrOsin0c0Jj6ewj8',
    appId: '1:1094370169228:ios:1845a568848339751e06a9',
    messagingSenderId: '1094370169228',
    projectId: 'lifelink-a3cbe',
    storageBucket: 'lifelink-a3cbe.firebasestorage.app',
    iosBundleId: 'com.example.organAndBloodDonation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM6-bzcHqUm-QM4ocv4Spy-ESyOHI1oi8',
    appId: '1:1094370169228:web:8057257cff2de2771e06a9',
    messagingSenderId: '1094370169228',
    projectId: 'lifelink-a3cbe',
    authDomain: 'lifelink-a3cbe.firebaseapp.com',
    storageBucket: 'lifelink-a3cbe.firebasestorage.app',
    measurementId: 'G-6J4851T2C0',
  );
}
